spring.application.name=health-management-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/health-management
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

calorieninjas.api.key=4JNqQpq5lec0V4JAylJlCg==yAgkBEd0T9gDBIcy
apininjas.api.key=j8sdZ1VhGQ29JQqqEdoRfl8UpmABrav9OubebzjK

calorieninjas.api.key=4JNqQpq5lec0V4JAylJlCg==yAgkBEd0T9gDBIcy
apininjas.api.key=j8sdZ1VhGQ29JQqqEdoRfl8UpmABrav9OubebzjK
