spring.application.name=health-management-backend
spring.datasource.url=jdbc:postgresql://dpg-d88n69p9rddc738k3if0-a.oregon-postgres.render.com/healthmanagement_ppad
spring.datasource.username=healthmanagement_ppad_user
spring.datasource.password=9RuMOW6rIVxolKuj5e5xP3J4XKh9H3iY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
